### ISSUE TITLE
Suggested corrections for the German translation

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#15]
Hi, below are my suggested corrections for the German translation. Unfortunately formatting or track changes doesn't seem possible with this feedback form. Therefore I will highlight the corrections with "+++".

In diesem Artikel
1.	Erstellen und Verwalten einer Microsoft 365-Gruppe mit dynamischer Mitgliedschaft
2.	Erstellen eines neuen Teams mit Ihrer Microsoft 365-Gruppe
3.	Anwenden einer dynamischen Mitgliedschaft auf ein vorhandenes Team
4.	Änderungen des Clientverhaltens

Microsoft Teams unterstützt Teams, die Microsoft 365-Gruppen zugeordnet sind, mithilfe der dynamischen Mitgliedschaft. Mit der dynamischen Mitgliedschaft kann die Mitgliedschaft in einem Team durch eine oder mehrere Regeln definiert werden, die in Azure Active Directory (Azure AD) nach bestimmten Benutzerattributen suchen. Benutzer werden automatisch zu den richtigen Teams hinzugefügt oder entfernt, wenn sich Benutzerattribute ändern oder Benutzer dem Mandanten beitreten und ihn +++verlassen+++.
Mit der dynamischen Mitgliedschaft können Sie Teams für bestimmte Kohorten von Benutzern in Ihrer Organisation einrichten. Mögliche Szenarien sind:
•	In einem Krankenhaus können unterschiedliche Teams für Krankenschwestern, Ärzte und Chirurgen zur Übertragung von Kommunikationen erstellt werden. Dies ist besonders wichtig, wenn das Krankenhaus auf temporäre Mitarbeiter angewiesen ist.
•	Eine Universität kann ein Team für alle Dozenten innerhalb eines bestimmten Kollegiums erstellen, einschließlich einer +++Dozentengruppe+++, die sich häufig ändert.
•	Eine Fluglinie möchte für jeden Flug ein Team erstellen (wie einen +++Dienstagnachmittag+++ nonstop von Chicago nach Atlanta) und +++eine häufig wechselnde Flight Crew automatisch zuweisen oder entfernen lassen.+++
Mithilfe dieser Funktion werden die Mitglieder eines bestimmten Teams automatisch basierend auf einem bestimmten Satz von Kriterien aktualisiert, anstatt die Mitgliedschaft manuell zu verwalten. Hierfür sind Azure AD Premium P1-Lizenzen erforderlich, und die Teammitgliedschaft kann von einem +++Mandantenadministrator+++ für die Azure AD-Eigenschaften jedes Benutzers zugewiesen werden, vorausgesetzt, Sie verfügen über einen Mandanten und ein Administratorkonto.
Microsoft Teams kann zwischen ein paar Minuten und bis zu zwei Stunden benötigen, um dynamische Mitgliedschaftsänderungen anzuzeigen, sobald Sie in der Microsoft 365-Gruppe für ein Team wirksam werden.
Erstellen und Verwalten einer Microsoft 365-Gruppe mit dynamischer Mitgliedschaft
Wenn Sie als +++Mandantenadministrator+++ angemeldet sind, folgen Sie den Anweisungen unter Erstellen einer dynamischen Gruppe und Überprüfen des Status. Beziehen Sie sich bei Bedarf auf Dynamische Mitgliedschaftsregeln für Gruppen in Azure Active Directory.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6a578ddb-6494-9bda-529e-0156e5ab7c30
* Version Independent ID: 57d519c9-90f0-873d-ffef-589f0b3b3ac9
* Content: [Übersicht über dynamische Mitgliedschaft für Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/dynamic-memberships)
* Content Source: [Teams/dynamic-memberships.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/dynamic-memberships.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by TinaMcN** [comment]
@SilviaEid thank you for the feedback.  I sent the article to be human translated which will take 2-3 days.  Hopefully that will fix the issues.

**Comment by TinaMcN** [comment]
Hi @SilviaEid the article has been human translated and the translators double checked that the issues you reported are fixed.  I'll close this issue now, feel free to reopen or create a new issue if everything is not fixed.  Thanks again for providing the feedback, it's very much appreciated.
