### ISSUE TITLE
erare humanum est

### ISSUE THREAD

**Issue by Wessse** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#16]
was bitte bedeutet das Wort : handlungsbehbare ????

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4f34a4f9-bb6f-03e9-9c11-bb2f43dd9aeb
* Version Independent ID: a6e1ee45-8ce4-96b4-21ad-90ca8af646c4
* Content: [Integration von Teams und Outlook-E-Mail - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-outlook-email-integration)
* Content Source: [Teams/teams-outlook-email-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/teams-outlook-email-integration.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by TinaMcN** [comment]
@Wessse Vielen Dank, dass Sie über dieses Problem berichtet haben. Es scheint ein Problem mit unserem maschinellen Übersetzungstool zu sein. Ich schickte den Artikel, um von Menschen übersetzt zu werden.

**Comment by TinaMcN** [comment]
@Wessse Der Artikel wird nun von einem Menschen übersetzt.  Können Sie bitte überprüfen, ob das Problem jetzt behoben ist?

**Comment by weyCC81** [comment]
erare humanum est (lat.) = Irren ist menschlich
