### ISSUE TITLE
Cant't find the add-on in "Enterprise applications > All applications"

### ISSUE THREAD

**Issue by pwanning** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#2]
We (role global admin) can't find the add-on in the application list. What are we missing?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4b322a66-bd92-7a04-8822-0d3f72786cfa
* Version Independent ID: e731eeb0-825a-f6d2-f639-4bb633d12963
* Content: [Einrichten des Microsoft Teams-Besprechungs-Add-ons für Google Workspace - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/add-gsuite-thru-aad)
* Content Source: [Teams/add-gsuite-thru-aad.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/add-gsuite-thru-aad.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
@pwanning 
Thank you for your comment. It appears that the release was pulled. We've removed the article. Cindy

**Comment by TinaMcN** [comment]
@cichur thank you for the information.  @pwanning fyi the German article should be removed by tomorrow.

**Comment by TinaMcN** [comment]
@pwanning closing this issue.  Please let us know if you discover any other issues with the German Teams documentation.
