### ISSUE TITLE
Please add more details about proxy authenticatoin and TURN/TCP with ProxyServer

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#20]
I know, that proxy are not ecommended and direct UDP is best for a good audio/video performance. true. 
But this page does not say, that proxy servers are forbidden or not working or not supported. It is only a "not recommended" and my customers then asks me, does it work.

Can Teams use a HTTP proxy for authenticatoin/login using HTTP -> YES
Can teams handle a proxy server who is asking for credentials (or have a signin portal) ?
teams is not only talking RTP over UDP for Audio/Video etc.  It can aso use TLS over 443 to work in networks without UDP. But is this traffic also able to use a HTTP-Proxy, and a proxy with authentication ?

Some clarification would be great here about whats supported with teams.
(and everything not written is not supported, i know)

Frank
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 826084d1-06f7-e837-bcfc-d86d427288f6
* Version Independent ID: 9b36168e-d398-0188-c510-4dc5dd5f9563
* Content: [Proxyserver für Skype for Business Online und Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/proxy-servers-for-skype-for-business-online)
* Content Source: [Teams/proxy-servers-for-skype-for-business-online.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/proxy-servers-for-skype-for-business-online.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by TinaMcN** [comment]
@tonysmit this feedback was submitted via the German page but is regarding the source content.  Can you please help answer the questions from @FrankCarius ?

**Comment by TinaMcN** [comment]
@tonysmit can you help with this question?

**Comment by tonysmit** [comment]
@TinaMcN - pinging some folks. Please hold..... :)
