### ISSUE TITLE
embarassing translation of partner names

### ISSUE THREAD

**Issue by MartinRinas** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#21]
The german translation of this page translated the partner name 'kollektive' to 'Sammelklage' . We shouldn't be tranlsating brand names and the german translation is 'class action lawsuit' - which doesn't make it better.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [Was sind Liveereignisse in Microsoft Teams? - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-live-events/what-are-teams-live-events?source=docs#feedback)
* Content Source: [Teams/teams-live-events/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/teams-live-events/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by TinaMcN** [comment]
@MartinRinas thank you for reporting this.  It appears to be a machine translation problem.  I sent the article, including the art pieces to be human translated, it should be fixed in a few days.

**Comment by TinaMcN** [comment]
@MartinRinas the article has been updated with human translated art.  Thanks again for reporting it.  Please close this issue if it looks ok to you.

**Comment by MartinRinas** [comment]
yes much better, thank you!
