### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by DanBusiness** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#24]
Bitte den Link im1. Abschnitt zum "Teams Integrations" Schaubild anpassen, dieser hat den selben Link, wie Voice!
Danke

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Poster zu IT-Architektur und Sprachlösungen von Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by TinaMcN** [comment]
Hi @DanBusiness, vielen Dank für Ihr Feedback.  Ich habe die Links auf der Seite überprüft und sie scheinen jetzt zu funktionieren und auf die richtigen Postern zu verlinken.  Funktionieren sie jetzt bei Ihnen?
