### ISSUE TITLE
Privacy Shield is obsolete! Pls correct!

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#25]
The page says:
For transfers of personal data from the EEA, EU, Switzerland, and the UK, Microsoft is certified to the EU-U.S. and Swiss-U.S. **Privacy Shield** Frameworks and the commitments they entail.

After Schrems 2 this is invalid. pls correct as in DPA from JULY 2020!

Ralf (NSO Germany)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cd0e0f68-d088-d0b7-cbb7-56bb16e4026f
* Version Independent ID: 8a107028-31a6-6821-a150-1ebdd7a7d440
* Content: [Microsoft Teams – Datenschutz - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-privacy)
* Content Source: [Teams/teams-privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/teams-privacy.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by TinaMcN** [comment]
@gitralf thank you for sharing this feedback.  @MicrosoftHeidi can you please advise if this section needs to be updated in the English article?
![image](https://user-images.githubusercontent.com/53281468/126185608-9f4c0aa6-315c-4c11-9671-de84df864047.png)
