### ISSUE TITLE
Please check german translation, "Surrouble" and "Surble" are no german words.

### ISSUE THREAD

**Issue by raho27** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#26]
https://docs.microsoft.com/de-de/microsoftteams/direct-routing-survivable-branch-appliance contains various incomprehensible translations of "Survivable Branch Appliance", e.g. "Surrouble Branch Appliance" and "Surble Branch Appliance". Please check this translation, in the current state it's nearly not usable for non-English readers. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 183fc921-e9b1-cc74-2bcb-26d32b994919
* Version Independent ID: 1765bda3-dd62-76d7-1e2d-9f5496ac9094
* Content: [Direct Routing SBA - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/direct-routing-survivable-branch-appliance)
* Content Source: [Teams/direct-routing-survivable-branch-appliance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/direct-routing-survivable-branch-appliance.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by TinaMcN** [comment]
@raho27 thank you for letting us know of this issue.   It certainly appears to be an issue with the machine translation.  I sent the article to be human translated and it should be complete in about 3 days.

**Comment by TinaMcN** [comment]
@raho27 the article has now been human translated for German and the correct term is being used. Please close if it looks ok to you now. https://docs.microsoft.com/de-de/microsoftteams/direct-routing-survivable-branch-appliance Thanks again for telling us about the issue and let us know if you notice any other problems with the German Teams content.
