### ISSUE TITLE
"Breakout rooms" should be translated to "Gruppenräume"

### ISSUE THREAD

**Issue by garelli99** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#27]
the term "breakout rooms" translates in German to "Gruppenräume"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d5323da5-6ed3-248c-ee0c-018e7ea29b26
* Version Independent ID: d9a3fcb1-2acd-598b-be74-628f0506484d
* Content: [Verwenden von Halteräumen in Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/using-breakout-rooms)
* Content Source: [Teams/using-breakout-rooms.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/using-breakout-rooms.md)
* Service: **msteams**
* GitHub Login: @ricardo-msft
* Microsoft Alias: **riwilki**

**Comment by TinaMcN** [comment]
@garelli99 thank you for reporting this issue.  You are totally correct, Gruppenräume is the correct term.  It appears to be an issue with our machine translation.  I sent the article to be human translated and hopefully it will be fixed within a week.

**Comment by TinaMcN** [comment]
@garelli99 the article has now been human translated for German and the correct term is being used.   Please close if it looks ok to you now.  https://docs.microsoft.com/de-de/microsoftteams/using-breakout-rooms  Thanks again for telling us about the issue and let us know if you notice any other problems with the German Teams content.
