### ISSUE TITLE
General feedback for the German "Support remote workers using Microsoft Teams" article

### ISSUE THREAD

**Issue by d-Rickyy-b** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#3]
Hi everyone,

since I was [asked](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5849#issuecomment-740411383) by @TinaMcN to give my feedback on the "Teams" articles, I am just going ahead to do so. I'll group multiple issues with this article into one GitHub issue, if that's okay. I think that saves time.

1. In the ["Anleitungen für IT-Administratoren"](https://docs.microsoft.com/de-de/microsoftteams/support-remote-work-with-teams#it-admin-guidance) paragraph, the last sentence reads "[...] unter Zusätzlicher Ressourcen zur Unterstützung von Remotemitarbeitern weiter unten.", which is also the heading of (and links to) the paragraph [here](https://docs.microsoft.com/de-de/microsoftteams/support-remote-work-with-teams#additional-resources-for-supporting-remote-workers). This is a grammatical issue (genitive instead of nominative) for the word "Zusätzlicher". 
**Fix:** It should say "Zusätzliche".
2. The third "recent article" below the ["Zusätzlicher Ressourcen zur Unterstützung von Remotemitarbeitern"](https://docs.microsoft.com/de-de/microsoftteams/support-remote-work-with-teams#additional-resources-for-supporting-remote-workers) heading, is a [broken link](https://www.microsoft.com/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/) - but also on the [English version](https://www.microsoft.com/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/) of this site.
**Fix:** Use working link
3. Below "5. Make sure your employees [...]" the second list item says (in English) "Read this timely blog". I'd think that "timely" in this context means something like "recently"/"just released". Apart from being 'not that timely anymore' ;) this is translated as "Lesen Sie den zur richtigen Zeit veröffentlichten Blogbeitrag [...]". This doesn't sound correct since "zur richtigen Zeit" means "at the right time".
**Fix:** Rephrase to something like "Lesen Sie den kürzlich veröffentlichten Blogbeitrag [...]"
4. Two list items below 3) it says "Sofern Ihr Standort China ist" - this doesn't feel like a very natural sentence.
**Fix:** Rephrase to something like "Sofern Sie sich in China befinden" or "Sofern sich Ihr Standort in China befindet"
5. Below "6. Sicherheit, wenn jeder von zu Hause aus arbeitet", there is a link to "Remotearbeit und Sicherheit – Anleitung für CISOs" which is a link to an English only article as it seems. All the other English articles were linked with their English name and got a translated article name next to it in parentheses.
**Fix:** Display English article name with the German translation next to it.
6. This might not be the scope but: Two items below that it references an article "Optimieren der Microsoft 365- oder Office 365-Konnektivität für Remotebenutzer mithilfe des geteilten VPN-Tunnels". Even the [German wikipedia page](https://de.wikipedia.org/wiki/Split_Tunneling) for split tunneling uses the English term. I basically have nobody heard using the term either. Also google returns 4.5 million German results for "split tunneling" opposed to 387k German results for "geteilter VPN-Tunnel" - and judging from the first page of results, some of them are found because of references to the MS docs.
**Fix:** Rename the article (and link) to "[...] Split Tunneling"
7. The article "Vier Tipps für die Arbeit mit Microsoft Teams von zu Hause aus" linked from 9) is also an English article with a German title (on this doc page).
**Fix:** Use English title with German translation in parentheses.
8. Under 11) it says "Senden Sie Informationen zu den Fernarbeits- sowie Integritäts- und Sicherheitsrichtlinien Ihrer Organisation." In English it says "[...] and health and safety policies." I guess that 'health' literally means human health, not system health/integrity. If not, please ignore this point.
**Fix:** Exchange "Integritäts-" with "Gesundheits-" 
9. Under 14) it says "Check out Teams-certified devices for personal and shared spaces.", in German "[...] für private und freigegebene Bereiche an." I think "personal and shared spaces" refer to personal offices and shared offices/meeting rooms and hence referring to headsets and loud speakers.
**Fix:** Replace "freigegebene" with something like "geteilte"

I hope this feedback helps you already. If I find more time, I'll check the other articles as well. But I can't promise anything for now.
In general this site feels quite machine translated (or translated by a non native speaker). It's not bad in general - in many cases it's just not how a human would phrase those sentences imho. Still everything is understandable and readable.

Feel free to ask any questions regarding my above points.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Unterstützung von Remotemitarbeitern in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/support-remote-work-with-teams#additional-resources-for-supporting-remote-workers)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by TinaMcN** [comment]
@d-Rickyy-b thank you so much for all this detailed feedback, really appreciate you taking the time!.  I passed on to the localizers for them to review and implement, I'll let you know if they have questions on any of your points.

**Comment by TinaMcN** [comment]
@d-Rickyy-b most of the issues you reported have now been fixed.  The only one that hasn't is #2, the link in both the German + English versions are working ok for me.   Can you confirm that the highlighted one is the issue and is it still not working for you?
![image](https://user-images.githubusercontent.com/53281468/102926850-9ac80300-444a-11eb-94bb-c25d0ab6d677.png)
Thanks again for the very valuable feedback!

**Comment by d-Rickyy-b** [comment]
> The only one that hasn't is #2, the link in both the German + English versions are working ok for me. Can you confirm that the highlighted one is the issue and is it still not working for you?

Yes exactly that one. But I just noticed that the english version works perfectly now - but the German one leads to a 404 page.

Working now: https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/

Still broken for me: https://www.microsoft.com/de-de/microsoft-365/blog/2020/03/12/top-9-ways-microsoft-it-enabling-remote-work-employees/

![grafik](https://user-images.githubusercontent.com/5798157/102937196-e4940600-44a9-11eb-93ca-7dcf94633cd3.png)

Even ["WhereGoes"](https://wheregoes.com/trace/) drops an error:

![grafik](https://user-images.githubusercontent.com/5798157/102937253-02fa0180-44aa-11eb-9dc1-f9ab8f827ff4.png)


> Thanks again for the very valuable feedback!

You are very welcome. Glad I can help making the docs more accessible by others.

**Comment by d-Rickyy-b** [comment]
> @d-Rickyy-b most of the issues you reported have now been fixed. The only one that hasn't is #2 [...]

I just noticed that the heading "Zusätzlicher Ressourcen zur Unterstützung von Remotemitarbeitern" is still contained in the article. It's only the reference to the section that has been fixed to "Zusätzliche". Maybe you can poke the localizers again :)

**Comment by TinaMcN** [comment]
@d-Rickyy-b I created this PR for the English article to add en-us to the link https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6403   Usually it's ok to use language neutral URLS (no en-us) but obviously not in this case.  Good catch!   I 'll ask the localizers to fix that remaining issue :-)

**Comment by TinaMcN** [comment]
@d-Rickyy-b the heading has been changed to Zusätzliche Ressourcen zur Unterstützung von Remotemitarbeitern.   It may be a while before the broken link is fixed due to people being on vacation.   Happy Holidays!
