### ISSUE TITLE
Microsoft-Telefonielösungen Poster

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#5]
Hi,

the link to the poster under "Microsoft-Telefonielösungen" leads to an error page.

Best regards,

Silvia

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ad3ad624-9792-91b7-c85f-09b839b1ea44
* Version Independent ID: e8288f91-11bd-599b-8a88-074917b315a4
* Content: [Microsoft Teams IT-Architektur- und Telefonielösungen Poster - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/teams-architecture-solutions-posters)
* Content Source: [Teams/teams-architecture-solutions-posters.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/teams-architecture-solutions-posters.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by TinaMcN** [comment]
@SilviaEid thank you for the feedback. The article has now been human translated and the link appears to be working.

**Comment by TinaMcN** [comment]
Hi @SilviaEid I'm closing this issue as the problem appears to be fixed.  Thanks again for reporting it.
