### ISSUE TITLE
Anleitungen für IT-Administratoren

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#6]
Hi,

in the below paragraph, the word „hat“ needs to be removed, as the customer needs a paid subscription that includes Teams, not a paid subscription that has included teams. Besides the sentences should be separated by a period.

Original:
Anleitungen für IT-Administratoren
•	Stellen Sie sicher, dass alle Benutzer auf Teams zugreifen können, nutzen Sie dazu ein kostenpflichtiges Abonnement, das Teams beinhaltet >>>>>>hat<<<<<<

With changes:
Anleitungen für IT-Administratoren
•	Stellen Sie sicher, dass alle Benutzer auf Teams zugreifen können. Nutzen Sie dazu ein kostenpflichtiges Abonnement, das Teams beinhaltet.

Best regards,
Silvia Eid

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3cdf3243-40dc-708c-cefc-8be68491a3be
* Version Independent ID: 0fc81593-de9a-c453-4a1c-ec1ebbfe2ecf
* Content: [Unterstützung von Remotemitarbeitern in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/support-remote-work-with-teams)
* Content Source: [Teams/support-remote-work-with-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/support-remote-work-with-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by TinaMcN** [comment]
@SilviaEid thanks for the feedback, it is fixed now.
