### ISSUE TITLE
Teams rooms vs. Teams-Räume

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#7]
Hi,

in this article sometimes Teams Rooms are called "Teams rooms", which looks very strange, and sometimes Teams Rooms has been translated with "Teams-Räume". 

Best regards,

Silvia Eid
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 752a6dc8-4018-88aa-faa4-c07c1c0a1719
* Version Independent ID: 7d6d29c5-f699-2abd-71c2-7c49061dd068
* Content: [Administrator Schulungsressourcen – Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/itadmin-readiness)
* Content Source: [Teams/ITAdmin-readiness.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/ITAdmin-readiness.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by TinaMcN** [comment]
@SilviaEid thank you for the feedback. I sent the article to be human translated which will take 2-3 days. Hopefully that will fix the issues.

**Comment by TinaMcN** [comment]
Hi @SilviaEid the article has been human translated and the translators double checked that the issue you reported are fixed.  I'll close this issue now, feel free to reopen or create a new issue if everything is not fixed.  Thanks again for providing the feedback, it's very much appreciated.
