### ISSUE TITLE
Teams sessions at Ignite 2020 - corrected translations

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-DE#8]
Hi,

In this article app has sometimes been translated into “APP” and sometimes into “app”. “App” would be correct.
The column “Abstract” has been translated into “Abstrakt”, which we do not use in this context. My suggestions would be “Zusammenfassung” or “Kurzfassung”.
The columen “Level” has been translated into “Ebene”, which is not correct in this context. I would leave it as it is in English: “Level”.
Besides there are translation errors in the following paragraphs in the table. I have marked the original translation as "Original" and my suggested corrected version as "Corrected"  (I only corrected the paragraphs that really sound incorrect and/or are not understandable, not the ones with smaller errors):

Original:
Das Aktivieren von sicheren, Remote Arbeit ist der Anfang. Informieren Sie sich in dieser Sitzung über die neuesten Features und Funktionen von Teams in Bezug auf Sicherheit und Compliance. Wir werden uns mit der Nutzung der Intelligence und der Stärke von Microsoft 365 in Teams belegen, um Ihre Organisation sicher und kompatibel zu halten. Zu den Themen gehören das Schützen von Informationen vor Datenverlusten, das Aktivieren von sicheren und integrativen Besprechungen sowie das aufrecht erhalten einer kompatiblen Organisation über die weltweiten Vorschriften und geschäftlichen Anforderungen hinweg.
Corrected:
Das Aktivieren sicherer Remote-Arbeit ist der Anfang. […]sowie das Aufrechterhalten einer kompatiblen Organisation über die weltweiten Vorschriften und geschäftlichen Anforderungen hinweg.

Original:
Gehen Sie tiefer mit anrufen, während wir die neue Anruf Erfahrung erforschen, weitere Informationen zu Collaborative Calling, E911, Location Based Routing und anderen Funktionen. Erfahren Sie, wie Anrufe für Ihre erweiterten Szenarien bereit stehen, unabhängig von der Größe Ihres Unternehmens.
Corrected:
Vertiefen Sie das Thema Anrufe und entdecken Sie mit uns die neue Anruf-Erfahrung, weitere Informationen zu Collaborative Calling, E911, Location Based Routing und anderen Funktionen. […]

Original:
Microsoft Teams-Geräte für freigegebene Speicherorte
Corrected
Microsoft Teams-Geräte für gemeinsame Arbeitsbereiche

Original:
Microsoft Teams-Geräte wurden entwickelt, um Personen zu helfen, die Leistungsfähigkeit von Teams zu maximieren und den Abstand zwischen Remote-und freigegebenen Arbeitsbereichen zu überwinden. Durch eine Kombination aus Teams-Besprechungsfunktionen, kundenorientierten Raumerfahrungen und branchenführender Hardware profitieren Benutzer von reibungslosen, integrativen und interaktiven Besprechungen, unabhängig davon, ob Sie an einem Remotestandort oder im Besprechungsraum teilnehmen. Erfahren Sie, wie freigegebene Speichergeräte wie Microsoft Teams-Chatrooms, Zusammenarbeits leisten und Surface Hub ihren Teams helfen können, in Verbindung mit dem Hybriden Arbeitsplatz zu bleiben.
Corrected:
Microsoft Teams-Geräte wurden entwickelt, um Personen zu helfen, die Leistungsfähigkeit von Teams zu maximieren und den Abstand zwischen Remote-und gemeinsamen Arbeitsbereichen zu überwinden. Durch eine Kombination aus Teams-Besprechungsfunktionen, kundenorientierten Raumerfahrungen und branchenführender Hardware profitieren Benutzer von reibungslosen, integrativen und interaktiven Besprechungen, unabhängig davon, ob Sie an einem Remotestandort oder im Besprechungsraum teilnehmen. Erfahren Sie, wie Geräte für gemeinsame Arbeitsbereiche wie Microsoft Teams Rooms, Videobars für die Zusammenarbeit und Surface Hub ihren Teams helfen können, weiter in Verbindung zu bleiben und zusammenzuarbeiten, quer durch den hybriden Arbeitsplatz.

Original:
Nehmen Sie an dieser Sitzung Teil, um den am besten geeigneten Ansatz basierend auf Ihren aktuellen Skype for Business-Implementierungs-und Unternehmenszielen zu ermitteln. Unabhängig davon, ob Sie ein Skype for Business Online-oder Server-Kunde sind, werden wir bewährte Methoden, Ressourcen und Anleitungen austauschen, um Microsoft Teams noch heute zu erreichen.
Corrected:
[…]
Unabhängig davon, ob Sie ein Skype for Business-Online oder –Server Kunde sind, werden wir bewährte Methoden, Ressourcen und Anleitungen austauschen, um Microsoft Teams noch heute zu erhalten.

Original:
Mit den Steuerelementen für Besprechungen und Videokonferenzen können Sie Ihre Teams sicher und umfassend treffen
Corrected:
Machen Sie Ihre Teams-Meetings sicher und integrative mit den Steuerelementen für Besprechungen und Videokonferenzen 

Original:
Nehmen Sie an dieser Sitzung Teil, um mehr über Besprechungs Sicherheit, Sicherheit und Moderation zu erfahren – einschließlich der Möglichkeit, alle Teilnehmer stummzuschalten, Funktionalitäten zu sprechen und Breakout Rooms zu konfigurieren. Wir werden auch Funktionen wie Reaktionen und angehobene Hände abdecken, die dazu beitragen, Besprechungen umfassender zu gestalten.
Corrected:
Nehmen Sie an dieser Sitzung teil, um mehr über Schutz, Sicherheit und Moderation in Meetings zu erfahren, einschließlich der Möglichkeit, alle Teilnehmer stummzuschalten, der Funktionalität, um nach der Erlaubnis zu sprechen zu fragen und des Konfigurierens von Breakout Rooms.

Original:
Erfahren Sie mehr über die Funktionen für die Anruf-und Besprechungs Plattform von Teams mit Updates für Microsoft Graph Cloud Communications-APIs, Contact Center und Compliance-Aufzeichnung sowie über kommende Nachrichten in anderen Platt Form Erfahrungen.
Corrected:
Erfahren Sie mehr über die Funktionen für die Anruf-und Besprechungs Plattform von Teams mit Updates für Microsoft Graph Cloud Communications-APIs, Contact Center und Compliance-Aufzeichnung sowie über kommende Neuigkeiten in anderen Plattform-Erfahrungen.

Original:
Nehmen Sie an dieser Sitzung Teil, um zu erfahren, wie Microsoft Teams nahtlos skalieren können, um die Bereitstellung von Ereignissen aller Art, von Unternehmens Rathaus, Schulungs-Webinaren bis hin zu Online Konferenzen, zu ermöglichen. Wir werden auch Vision und Roadmap für Funktionen freigeben, um Ihre virtuellen Besprechungen und Ereignisse zu skalieren und anzupassen.
Corrected:
Nehmen Sie an dieser Sitzung teil, um zu erfahren, wie Microsoft Teams nahtlos skaliert werden kann, um Sie bei der Bereitstellung aller Arten von Events zu unterstützen, von Town Hall Meetings, über Schulungs-Webinare, bis hin zu Onlinekonferenzen. Außerdem werden wir unsere Vision und Roadmap für Features zum Skalieren und Anpassen Ihrer virtuellen Meetings und Events mit Ihnen teilen.

Original:
Teams-Besprechungen entwickeln sich weiter und integrieren sich tief in das Kontinuum der Zusammenarbeit. Wenn Sie Besprechungen produktiver, sicherer und umfassender gestalten, können Sie mit der Innovation in Microsoft Teams Ihre Besprechungen besser vorbereiten, ausführen und optimieren. In dieser Sitzung werden bewährte Methoden vorgestellt, die Ihnen helfen, Ihre Besprechungen optimal zu nutzen und den Arbeitsfluss zu verbringen.
Corrected:
Teams-Besprechungen entwickeln sich weiter und integrieren sich tief in das Kontinuum der Zusammenarbeit. Wenn Sie Besprechungen produktiver, sicherer und umfassender gestalten, können Sie mit der Innovation in Microsoft Teams Ihre Besprechungen besser vorbereiten, ausführen und optimieren. In dieser Sitzung werden bewährte Methoden vorgestellt, die Ihnen helfen, Ihre Besprechungen optimal zu nutzen und im Arbeitsfluss zu bleiben.

Original:
Sehen Sie sich diese Hands an, um die Governance-Funktionen und-Tools zu demonstrieren, mit denen Sie die Benutzererfahrung von Microsoft Teams verwalten und Ihnen Vertrauen in die Sicherheit und Compliance Ihrer Informationen geben können. Umfasst die Konfiguration der Azure Active Director-Add-on-Funktionen.
Corrected:
Sehen Sie sich diese praktische Vorführung der Governance-Funktionen und –Tools an, die Ihre Endnutzer-Erfahrung in Teams verwalten und Ihnen Vertrauen in die Sicherheit und Compliance Ihrer Informationen geben werden. Beinhaltet die Konfiguration der Azure Active Directory Add-On Funktionalitäten.

Original:
Einführung in die Industrie – spezielle Szenarien und Funktionen für First-, gemeinnützige, Gesundheits-und mehr.
Corrected:
Einführung in speziellen Sektoren – besondere Szenarien und Features für Firstline Worker, gemeinnützige Organisationen, den Gesundheitssektor und mehr.

Original:
In dieser Szenario-basierten Sitzung werden die vorhandenen und neuen Features im Kontext der IT-Experten überprüft, die Sie bereitstellen müssen. Einschließlich Endbenutzer-und ITPro-Vorlagen, Mobile Features
Corrected:
In dieser Szenario-basierten Sitzung werden wir sowohl vorhandene, als auch neue Features für IT-Experten besprechen, die sie bereitstellen müssen. Einschließlich Vorlagen für Endnutzer und IT-Experten und Mobile Features.

Original:
In dieser Sitzung werden wir alle wichtigen Produkte und Ressourcen durchlaufen, die Ihnen helfen können, sicherzustellen, dass Ihr Team-Rollout erfolgreich ist. Von Tools und Ressourcen zu bewährten Methoden: diese Sitzung muss teilnehmen, wenn die Planung und Bereitstellung von Teams in Ihrer Aufgabenliste liegt!
Corrected:
In dieser Sitzung werden wir alle wichtigen Produkte und Ressourcen durchgehen, die Ihnen helfen können sicherzustellen, dass Ihre Bereitstellung von Teams erfolgreich ist. Von Tools und Ressourcen bis hin zu bewährten Methoden: diese Sitzung sollten Sie nicht verpassen, wenn die Planung und Bereitstellung von Teams auf Ihrer To-Do-Liste steht!

Original:
Anzeigen von Hands zu Demonstrationen rund um bewährte Methoden, die Ihnen beim Bereitstellen und Verwalten von Microsoft Teams über Endpunkt-Manager helfen
Corrected:
Schauen Sie sich praktische Vorführungen rund um bewährte Methoden an, die Ihnen beim Bereitstellen und Verwalten von Microsoft Teams mit dem Endpoint Manager helfen.

Original:
Grundlagen für die Verwaltung von Microsoft Teams Erweiterte Verwaltbarkeit-Steuerelemente
Corrected:
Grundlagen für die Verwaltung von Microsoft Teams; Steuerelemente für die Erweiterte Verwaltbarkeit

Original:
Die Bereitstellung einer sicheren Zusammenarbeit ist unerlässlich. Besuchen Sie uns, um eine Übersicht über die Sicherheits-und Compliance-Funktionen für Microsoft Teams aus einer ITPro Perspektive zu finden. Richtlinienverwaltung, Inhaltsverwaltung, Aufbewahrungsverfahren, Kommunikationsrichtlinien und mehr werden abgedeckt. Sehen Sie sich das vollständige Kompliment der Funktionen für sichere, kompatible Zusammenarbeit an!
Corrected:
Die Bereitstellung einer sicheren Zusammenarbeit ist unerlässlich. Besuchen Sie uns, um eine Übersicht über die Sicherheits- und Compliance-Funktionen für Microsoft Teams aus einer ITPro-Perspektive zu finden. Richtlinienverwaltung, Inhaltsverwaltung, Aufbewahrungsverfahren, Kommunikationsrichtlinien und mehr werden abgedeckt. Sehen Sie sich sämtliche Funktionen für sichere und konforme Zusammenarbeit an!

Original:
Um von ihrer besten Seite zu sein, müssen sich die Menschen dazu fühlen, in Ihrer persönlichen Zeit anwesend zu sein, und mit den richtigen Tools dazu befähigt werden, Sie für den Erfolg in ihrer Rolle einzusetzen. Erfahren Sie, wie Teams Zusammenarbeit in Teams einbeziehen können, indem Sie sicherstellen, dass jeder in der für Sie am besten geeigneten Weise zusammenarbeiten kann, während gleichzeitig Arbeit und Leben ausgeglichen werden.
Corrected:
Um sein Bestes zu geben, muss man sich einbezogen fühlen, motiviert werden, während Ihrer persönlichen Zeit anwesend zu sein und von den richtigen Tools unterstützt werden, die ihnen dabei helfen, in ihrer Rolle erfolgreich zu sein. Erfahren Sie, wie Teams die integrative Teamarbeit unterstützen kann, indem sichergestellt wird, dass alle auf die individuell geeignete Weise zusammenarbeiten und Arbeit und Privatleben in Einklang bringen.

Original:
Industrie [the title]
Corrected:
Spezielle Sektoren

Original:
Zusammenarbeit und Kommunikation mit Microsoft Teams in der Regierung
Corrected:
Zusammenarbeit und Kommunikation mit Microsoft Teams im öffentlichen Sektor

Original:
Staats-, Orts-und Bundesbehörden Nutzen Microsoft Teams, um Ihre Fähigkeit zur Zusammenarbeit zu verbessern und Ihre Reaktionszeiten und Bürgerengagements zu verbessern. Erfahren Sie, wie Sie die Nutzung vorhandener Features maximieren, was als nächstes kommt, und unsere zukünftige Vision für Microsoft Teams in der Regierung.
Corrected:
Kommunale-, Länder- und Bundesbehörden nutzen Microsoft Teams, um die Zusammenarbeit zu verbessern und Ihre Reaktionszeiten und bürgerschaftliches Engagement zu verbessern. Erfahren Sie, wie Sie Ihre Nutzung vorhandener Features maximieren, was als Nächstes kommt und was unsere Vision für die Zukunft für Microsoft Teams im öffentlichen Sektor ist.

Original:
First-Worker [the title]
Corrected:
Firstline Worker

Original:
Aktivieren von Business Continuity für Ihre First-Workforce-Mitarbeiter mit Microsoft Teams
Corrected:
Aktivieren von Business Continuity für Ihre Firstline-Workforce mit Microsoft Teams

Original:
Da Organisationen ihre Vorgänge und Arbeitskräfte weiterhin so anpassen, dass die Geschäftskontinuität gewährleistet wird, unterstützen neue Funktionen in Microsoft Teams die Mitarbeiter von First work, die Kundenanforderungen zu erfüllen.Diese Sitzung konzentriert sich auf Schichten, Aufgaben und Kern Kommunikation zusammen mit Walkie Talkie-Funktionen, um eine sichere und zentralisierte Benutzeroberfläche zu schaffen, die Ihnen Zeit und Geld spart.
Corrected:
Während Organisationen ihre Abläufe und ihr Personal weiter anpassen, damit der Geschäftsbetrieb aufrechterhalten wird, helfen neue Funktionalitäten in Microsoft Teams Firstline Workern dabei, sich weiterhin auf die Erfüllung der Kundenanforderungen zu konzentrieren. Diese Sitzung konzentriert sich auf Schichten, Aufgaben , die Kernkommunikation und Walkie Talkie-Funktionen, die dabei helfen, eine sichere und zentralisierte Benutzererfahrung zu schaffen, die Ihnen Zeit und Geld spart.

Original:
Bereitstellen und Verwalten von Teams mit aktivierten Geräten, um den unterschiedlichen Anforderungen Ihrer First-Workforce-Mitarbeiter gerecht zu werden
Corrected:
Bereitstellen und Verwalten von Teams-fähigen Geräten zur Erfüllung der unterschiedlichen Anforderungen Ihrer Firstline-Workforce.

Original:
Hier erfahren Sie, wie Sie die ersten spezifischen Geräte bereitstellen, die neuen Möglichkeiten für die Arbeit von Arbeitskräften ermöglichen, sich auf den jeweiligen Job zu konzentrieren. In dieser exemplarischen Vorgehensweise werden Szenarien für Teams wie Walkie Talkie und freihändige Zusammenarbeit aufgeführt.
Corrected:
Erfahren Sie, wie Sie Firstline-spezifische Geräte bereitstellen, die Arbeitskräften neue
Möglichkeiten geben, sich auf Ihren Job zu konzentrieren. Diese Schritt-für-Schritt Anleitung beinhaltet Szenarien für Teams Walkie Talkie und die Zusammenarbeit über Freisprechgeräte. Go deeper with Calling as we explore the new calling experience, further information on Collaborative Calling, e911, Location Based Routing and other features.

Original:
Verwalten von verteilten First-Workforce-Mitarbeitern mit Funktionen im Microsoft 365 Admin Center
Corrected:
Verwalten verteilter Firstline-Workforces mit Funktionalitäten im Microsoft 365 Admin Center

Original:
Entdecken Sie bewährte Methoden und praktische Anleitungen rund um beliebte Szenarien für die IT-Bereitstellung und-Verwaltung in Microsoft 365 für First-work-Mitarbeiter. Erfahren Sie, wie Sie die richtige Erfahrung in Microsoft Teams erstellen und die Lösung erfolgreich für die Unterstützung ihrer First-Workforce-Mitarbeiter bereitstellen können.
Corrected:
Entdecken Sie bewährte Methoden und praktische Anleitungen rund um beliebte Szenarien für die IT-Bereitstellung und-Verwaltung in Microsoft 365 für Firstline Worker. Erfahren Sie, wie Sie die richtige Erfahrung in Microsoft Teams erstellen und die Lösung erfolgreich für die Unterstützung ihrer Firstline-Workforce bereitstellen können.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 026656ef-3309-f381-532c-51b3b443f206
* Version Independent ID: 8fb11047-1cb5-68de-b8cc-3e6a882ab3c0
* Content: [Teams-Sitzungen bei Ignite 2020 - Microsoft Teams](https://docs.microsoft.com/de-de/microsoftteams/ignite-2020-landing-page)
* Content Source: [Teams/ignite-2020-landing-page.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness.de-de/blob/live/Teams/ignite-2020-landing-page.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by TinaMcN** [comment]
@SilviaEid many thanks for the super detailed feedback.  I sent the article to be human translated which will take 2-3 days. Hopefully that will fix the issues.

**Comment by TinaMcN** [comment]
Hi @SilviaEid the article has been human translated and the translators double checked that the issues you reported are fixed.  I'll close this issue now, feel free to reopen or create a new issue if everything is not fixed.  Thanks again for providing the feedback, it's very much appreciated.
